name: McuLoginPlugin
version: 1.0.1
main: org.mcu.papermc.McuLoginPlugin
description: An example plugin
author: PaperMC
website: https://papermc.io
api-version: '1.20.5'
commands:
  login:
    description: "/login <password> - Login to the server"
    usage: "/login <password>"
    aliases: lg
