name: ExamplePlugin
version: 1.0.1
main: org.mcu.papermc.McuLoginPlugin
description: An example plugin
author: PaperMC
website: https://papermc.io
api-version: '1.20.5'
commands:
  bind:
    description: "/bind <token>"
    aliases: bd
  login:
    description: "/login <password>"
    aliases: bd
