name: McuLoginPlugin
version: 2.0.0
main: org.mcu.papermc.McuLoginPlugin
description: "MUC-paper¶Ë-¸½ÊôµÇÂ¼²å¼þ"
author: PaperMC
website: https://papermc.io
api-version: '1.20'
commands:
  login:
    description: "/login <password> - Login to the server"
    usage: "/login <password>"
    aliases: lg
